- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      echo "Starting deployment..."
      IMAGE_NAME="${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest"
      echo "Deploying image: $IMAGE_NAME"

      docker pull $IMAGE_NAME

      docker stop my-app || true
      docker rm my-app || true

      docker run -d \
        -p 5000:5000 \
        --name my-app \
        --restart unless-stopped \
        -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
        -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
        $IMAGE_NAME

      docker ps | grep my-app
      echo "Deployment completed!"
